version: 2

workflows:
  version: 2
  build:
    jobs:
      - build:
         filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: Disable jekyll builds
          command: touch ~/.nojekyll
      - run:
          name: Prepare Git Initialization
          command: |
            git config user.email "ci-build@example.domain"
            git config user.name "ci-build"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            npm install @11ty/eleventy -g
      - run: 
          name: Build Eleventy Site
          command: |
            npm install
            hexo generate # generate static files
      - add_ssh_keys:
          fingerprints:
            - "44:96:a5:95:1e:86:90:cf:e6:ef:67:e7:33:23:3b:0f"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist dist
