version: 2

workflows:
  version: 2
  build:
    jobs:
      - build:
         filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: Disable jekyll builds
          command: touch ~/.nojekyll
      - run:
          name: Prepare Git Initialization
          command: |
            git config user.email "ci-build@example.domain"
            git config user.name "ci-build"
      - run:
          name: Install and Configure Dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            npm install hexo-cli -g
      - run: 
          name: Install Hexo Site Dependencies
          command: npm install
      - run: 
          name: Generate Hexo Static Files
          command: hexo generate 
      - add_ssh_keys:
          fingerprints:
            - "34:65:f3:a6:58:55:cc:fa:29:96:44:73:e2:6a:f9:64"
      - run:
          name: Deploy Static Files to gh-pages Branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist public
